#!/usr/bin/env julia
# Potts BP q-sweep contraction-complexity probe.
#
# This uses the exact single-layer Potts graph from `run_bp.jl`:
#   - one factor per lattice site
#   - one variable per lattice bond
#   - bond dimension = q
#
# We do NOT run numerical BP here. We only ask GenericMessagePassing for the
# precomputed TreeSA contraction plans of the BP updates and read off tc/sc.
# That makes the q-sweep cheap and directly comparable to the TNMP sweep.

using GenericMessagePassing
const GMP = GenericMessagePassing
using OMEinsum: getixsv, getiyv
using OMEinsum.OMEinsumContractionOrders: IncidenceList, TreeSA, contraction_complexity
using Statistics: mean
using Serialization: serialize
using Printf: @sprintf
using Dates: now

include(joinpath(@__DIR__, "common.jl"))

const DEFAULT_Q_VALUES = [2, 4, 8, 16, 32]

progress(msg) = (println("[progress $(now())] $msg"); flush(stdout))

aggregate(values::AbstractVector{<:Real}) =
    isempty(values) ? (; count = 0, min = NaN, max = NaN, mean = NaN) :
    (; count = length(values), min = minimum(values), max = maximum(values), mean = mean(values))

fmt(x) = isnan(x) ? "-" : @sprintf("%.3f", x)

function linear_slope(xs::AbstractVector{<:Real}, ys::AbstractVector{<:Real})
    length(xs) == length(ys) || error("x/y length mismatch")
    mx = mean(xs)
    my = mean(ys)
    denom = sum((x - mx)^2 for x in xs)
    denom == 0 && return NaN
    return sum((x - mx) * (y - my) for (x, y) in zip(xs, ys)) / denom
end

function build_bp_graph(p::PottsParams)
    sites = all_sites(p.L)
    site2id = Dict{Tuple{Int,Int},Int}(s => i for (i, s) in enumerate(sites))

    edges = lattice_edges(p.L)
    edge2id = Dict{Any,Int}()
    for (i, e) in enumerate(edges)
        edge2id[minmax(e[1], e[2])] = i
    end

    ixs = Vector{Vector{Int}}(undef, length(sites))
    for (i, v) in enumerate(sites)
        nbrs = site_neighbors(v, p.L)
        ixs[i] = [edge2id[minmax(v, n)] for n in nbrs]
    end

    hyper = IncidenceList(Dict(i => ixs[i] for i in eachindex(ixs)))
    size_dict = Dict(i => p.q for i in 1:length(edges))

    return (; sites, site2id, edges, edge2id, ixs, hyper, size_dict)
end

function rows_for_q(p::PottsParams, optimizer)
    bp = build_bp_graph(p)
    ids = collect(eachindex(bp.edges))

    e2v_plans, v2e_plans = GMP.bp_precompute_plans(bp.hyper, bp.ixs, ids, bp.size_dict; optimizer = optimizer)

    e2v_rows = NamedTuple[]
    for ((e, v), plan) in e2v_plans
        cc = contraction_complexity(plan.eins, bp.size_dict)
        push!(e2v_rows, (; kind = "e2v", source = e, target = v, sc = cc.sc, tc = cc.tc,
            n_tensors = length(getixsv(plan.eins)), n_open_legs = length(getiyv(plan.eins))))
    end

    v2e_rows = NamedTuple[]
    for ((v, e), plan) in v2e_plans
        cc = contraction_complexity(plan.eins, bp.size_dict)
        push!(v2e_rows, (; kind = "v2e", source = v, target = e, sc = cc.sc, tc = cc.tc,
            n_tensors = length(getixsv(plan.eins)), n_open_legs = length(getiyv(plan.eins))))
    end

    center = bp.site2id[p.center]
    center_e2v = filter(r -> r.target == center, e2v_rows)
    center_v2e = filter(r -> r.source == center, v2e_rows)

    return (; bp, e2v_rows, v2e_rows, center_e2v, center_v2e)
end

function summarize(q::Int, rows)
    return (;
        q = q,
        n_e2v = length(rows.e2v_rows),
        n_v2e = length(rows.v2e_rows),
        e2v_tc = aggregate([r.tc for r in rows.e2v_rows]),
        e2v_sc = aggregate([r.sc for r in rows.e2v_rows]),
        v2e_tc = aggregate([r.tc for r in rows.v2e_rows]),
        v2e_sc = aggregate([r.sc for r in rows.v2e_rows]),
        center_e2v_tc = aggregate([r.tc for r in rows.center_e2v]),
        center_e2v_sc = aggregate([r.sc for r in rows.center_e2v]),
        center_v2e_tc = aggregate([r.tc for r in rows.center_v2e]),
        center_v2e_sc = aggregate([r.sc for r in rows.center_v2e]),
        all_tc = aggregate([r.tc for r in vcat(rows.e2v_rows, rows.v2e_rows)]),
        all_sc = aggregate([r.sc for r in vcat(rows.e2v_rows, rows.v2e_rows)]),
    )
end

function write_markdown(path, summaries, meta)
    open(path, "w") do io
        println(io, "# Potts BP q-sweep contraction complexity (TreeSA)")
        println(io)
        println(io, "Generated by [`bp_complexity_sweep.jl`](bp_complexity_sweep.jl).")
        println(io)
        println(io, "Model: single-layer classical q-state Potts on an open $(meta.L)x$(meta.L) ")
        println(io, "square lattice, bond dim = q, couplings = `$(meta.couplings)`. ")
        println(io)
        println(io, "This is the exact BP graph used by `run_bp.jl`, but only the TreeSA ")
        println(io, "contraction plans are measured. `tc` = log2(#multiply-adds), ")
        println(io, "`sc` = log2(largest intermediate size).")
        println(io)

        println(io, "## Edge -> site messages (e2v)")
        println(io)
        println(io, "| q | #msgs | tc min | tc mean | tc max | sc min | sc mean | sc max | center tc | center sc |")
        println(io, "|--:|------:|-------:|--------:|-------:|-------:|--------:|-------:|----------:|----------:|")
        for s in summaries
            println(io, "| $(s.q) | $(s.n_e2v) | $(fmt(s.e2v_tc.min)) | $(fmt(s.e2v_tc.mean)) | $(fmt(s.e2v_tc.max)) | $(fmt(s.e2v_sc.min)) | $(fmt(s.e2v_sc.mean)) | $(fmt(s.e2v_sc.max)) | $(fmt(s.center_e2v_tc.mean)) | $(fmt(s.center_e2v_sc.mean)) |")
        end
        println(io)

        println(io, "## Site -> edge messages (v2e)")
        println(io)
        println(io, "| q | #msgs | tc min | tc mean | tc max | sc min | sc mean | sc max | center tc | center sc |")
        println(io, "|--:|------:|-------:|--------:|-------:|-------:|--------:|-------:|----------:|----------:|")
        for s in summaries
            println(io, "| $(s.q) | $(s.n_v2e) | $(fmt(s.v2e_tc.min)) | $(fmt(s.v2e_tc.mean)) | $(fmt(s.v2e_tc.max)) | $(fmt(s.v2e_sc.min)) | $(fmt(s.v2e_sc.mean)) | $(fmt(s.v2e_sc.max)) | $(fmt(s.center_v2e_tc.mean)) | $(fmt(s.center_v2e_sc.mean)) |")
        end
        println(io)

        qs = [s.q for s in summaries]
        xs = log2.(qs)
        e2v_center_tc = [s.center_e2v_tc.mean for s in summaries]
        e2v_center_sc = [s.center_e2v_sc.mean for s in summaries]
        v2e_center_tc = [s.center_v2e_tc.mean for s in summaries]
        v2e_center_sc = [s.center_v2e_sc.mean for s in summaries]
        e2v_max_tc = [s.e2v_tc.max for s in summaries]
        e2v_max_sc = [s.e2v_sc.max for s in summaries]
        v2e_max_tc = [s.v2e_tc.max for s in summaries]
        v2e_max_sc = [s.v2e_sc.max for s in summaries]

        println(io, "## Log-log slopes vs q")
        println(io)
        println(io, "| line | tc slope | sc slope |")
        println(io, "|-----|---------:|---------:|")
        println(io, "| e2v center | $(fmt(linear_slope(xs, e2v_center_tc))) | $(fmt(linear_slope(xs, e2v_center_sc))) |")
        println(io, "| v2e center | $(fmt(linear_slope(xs, v2e_center_tc))) | $(fmt(linear_slope(xs, v2e_center_sc))) |")
        println(io, "| e2v max | $(fmt(linear_slope(xs, e2v_max_tc))) | $(fmt(linear_slope(xs, e2v_max_sc))) |")
        println(io, "| v2e max | $(fmt(linear_slope(xs, v2e_max_tc))) | $(fmt(linear_slope(xs, v2e_max_sc))) |")
        println(io)
    end
    return path
end

function main()
    args = ARGS
    L = parse_int_opt(args, "L", 10)
    couplings = parse_opt(args, "couplings", "ferro")
    q_str = parse_opt(args, "q-list", nothing)
    q_values = q_str === nothing ? DEFAULT_Q_VALUES : [parse(Int, strip(s)) for s in split(q_str, ",")]
    ntrials = parse_int_opt(args, "treesa-ntrials", 20)
    niters = parse_int_opt(args, "treesa-niters", 60)
    sc_target = parse_int_opt(args, "treesa-sc-target", 20)
    out_md = parse_opt(args, "out", joinpath(@__DIR__, "..", "results", "potts_bp_complexity_sweep.md"))
    out_jls = replace(out_md, r"\.md$" => ".jls")
    mkpath(dirname(out_md))

    optimizer = TreeSA(; ntrials = ntrials, niters = niters, sc_target = sc_target, βs = 1.0:1.0:18.0)

    progress("potts BP complexity sweep: L=$L couplings=$couplings q_values=$q_values " *
             "treesa(ntrials=$ntrials,niters=$niters,sc_target=$sc_target)")

    summaries = NamedTuple[]
    all_rows = Dict{Int,Any}()
    for q in q_values
        p = PottsParams(L, q, 1.0, default_field(q), grid_center(L), couplings)
        progress("q=$q: building BP plans")
        rows = rows_for_q(p, optimizer)
        all_rows[q] = rows
        s = summarize(q, rows)
        push!(summaries, s)
        progress("q=$q -> e2v center tc=$(fmt(s.center_e2v_tc.mean)) sc=$(fmt(s.center_e2v_sc.mean)) " *
                 "| v2e center tc=$(fmt(s.center_v2e_tc.mean)) sc=$(fmt(s.center_v2e_sc.mean))")
    end

    meta = (; L, couplings, q_values, ntrials, niters, sc_target)
    write_markdown(out_md, summaries, meta)
    open(out_jls, "w") do io
        serialize(io, (; meta, summaries, rows = all_rows))
    end
    progress("wrote $out_md")
    progress("wrote $out_jls")
    println("\nsaved markdown -> $out_md")
    println("saved jls      -> $out_jls")
    return summaries
end

if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    main()
end
