#!/usr/bin/env julia
# TreeSA contraction complexity for BP sub-TNs (cavity / neighborhood).
# BP works on single-site regions of the double-layer norm network, so the
# sub-TN is a single ket/bra site pair (interior degree-4). The incoming
# messages are rank-2 (they couple ket and bra together — blue triangles in the
# figures span both circles). The contraction is L-independent: only the virtual
# bond dimension χ matters.
#   - bp_cavity (message i→j):   green inter-layer bond intact; 1 open output
#     edge (split rank-1 red caps, one per layer) + 3 incoming rank-2 messages.
#   - bp_neighborhood (marginal i): green inter-layer bond intact;
#     4 incoming rank-2 messages.
# Conventions match gbp_contraction_sc.jl.

using Pkg
Pkg.activate(normpath(@__DIR__, ".."); io = devnull)

using OMEinsumContractionOrders:
    EinCode, optimize_code, contraction_complexity, TreeSA, peak_memory
using Printf: @printf

const DIM_GREEN = 2

mutable struct NetBuilder
    node_inds::Dict{Any, Vector{Int}}
    dims::Dict{Int, Int}
    nedge::Int
    ntri::Int
end
NetBuilder() = NetBuilder(Dict{Any, Vector{Int}}(), Dict{Int, Int}(), 0, 0)

node!(nb::NetBuilder, n) = get!(nb.node_inds, n, Int[])

function edge!(nb::NetBuilder, u, v, d::Int)
    nb.nedge += 1
    e = nb.nedge
    nb.dims[e] = d
    push!(node!(nb, u), e)
    push!(node!(nb, v), e)
    return e
end

function caps!(nb::NetBuilder, c, k::Int, d::Int)
    for _ in 1:k
        nb.ntri += 1
        edge!(nb, c, (:tri, nb.ntri), d)
    end
end

function eincode(nb::NetBuilder)
    nodes = collect(keys(nb.node_inds))
    ixs = [nb.node_inds[n] for n in nodes]
    return EinCode(ixs, Int[]), nb.dims, length(nodes)
end

max_input_log2(ec::EinCode, dims::Dict{Int, Int}) =
    maximum(ix -> isempty(ix) ? 0.0 : sum(l -> log2(dims[l]), ix), ec.ixs)

# A rank-2 incoming message: one tensor node coupling ket (T) and bra (B),
# with a χ leg to each layer.
function rank2_msg!(nb::NetBuilder, T, B, dim_chi::Int)
    nb.ntri += 1
    m = (:msg, nb.ntri)
    edge!(nb, T, m, dim_chi)
    edge!(nb, B, m, dim_chi)
    return m
end

# BP message update i→j: single ket/bra site, green bond intact, one open output
# edge (split rank-1 caps, one per layer) and 3 incoming rank-2 messages.
# Interior degree-4 site → 4 in-plane legs per layer.
function build_bp_cavity(dim_chi::Int; dim_green::Int = DIM_GREEN)
    nb = NetBuilder()
    T = (:T, 0, 0)
    B = (:B, 0, 0)
    edge!(nb, T, B, dim_green)          # inter-layer green bond intact
    caps!(nb, T, 1, dim_chi)            # open output leg (split rank-1, ket)
    caps!(nb, B, 1, dim_chi)            # open output leg (split rank-1, bra)
    for _ in 1:3
        rank2_msg!(nb, T, B, dim_chi)   # 3 incoming rank-2 messages
    end
    return nb
end

# BP single-site marginal: green inter-layer bond intact, 4 incoming rank-2
# messages coupling ket and bra on each in-plane edge.
function build_bp_neighborhood(dim_chi::Int; dim_green::Int = DIM_GREEN)
    nb = NetBuilder()
    T = (:T, 0, 0)
    B = (:B, 0, 0)
    edge!(nb, T, B, dim_green)          # inter-layer green bond intact
    for _ in 1:4
        rank2_msg!(nb, T, B, dim_chi)   # 4 incoming rank-2 messages
    end
    return nb
end

function report(nb::NetBuilder; opt = TreeSA(; ntrials = 20, niters = 60, βs = 1.0:1.0:18.0))
    ec, dims, nnodes = eincode(nb)
    code = optimize_code(ec, dims, opt)
    cc = contraction_complexity(code, dims)
    return (; tensors = nnodes, max_input = max_input_log2(ec, dims),
        sc = cc.sc, peak_memory = log2(peak_memory(code, dims)), tc = cc.tc)
end

function main()
    chi_values = [4, 8, 16, 32]

    println("=== BP sub-TN contraction complexity (TreeSA) ===")
    println("green bond = dim $DIM_GREEN, black bond = dim χ")
    println("single-site double-layer region (L-independent)\n")

    results = Dict{String, Vector{NamedTuple}}()
    for chi in chi_values
        for (builder, label) in (
            (build_bp_cavity, "bp_cavity"),
            (build_bp_neighborhood, "bp_neighborhood"),
        )
            r = report(builder(chi))
            push!(get!(results, label, NamedTuple[]), (; chi, r...))
            @printf("%-18s χ=%2d | tensors=%2d | max_input=2^%-4.1f | sc=2^%-4.1f | tc=2^%.1f\n",
                label, chi, r.tensors, r.max_input, r.sc, r.tc)
        end
    end

    md_path = joinpath(@__DIR__, "bp_contraction_sc_results.md")
    open(md_path, "w") do io
        println(io, "# BP contraction complexity (TreeSA)\n")
        println(io, "Generated by [`bp_contraction_sc.jl`](bp_contraction_sc.jl).\n")
        println(io, "BP regions are single sites, so the sub-TN does not grow with L; only χ matters.\n")
        println(io, "| Figure | χ=4 sc | χ=4 tc | χ=8 sc | χ=8 tc | χ=16 sc | χ=16 tc | χ=32 sc | χ=32 tc |")
        println(io, "|--------|-------:|-------:|-------:|-------:|--------:|--------:|--------:|--------:|")
        for label in ("bp_cavity", "bp_neighborhood")
            rows = results[label]
            vals = String[]
            for chi in chi_values
                row = only(filter(r -> r.chi == chi, rows))
                push!(vals, string(round(row.sc; digits = 3)))
                push!(vals, string(round(row.tc; digits = 3)))
            end
            println(io, "| $label | " * join(vals, " | ") * " |")
        end
    end
    println("\nWrote $md_path")
end

main()
